#!/bin/python3

from src.SharedFunctions import *
from src.Initialization import *
from src.DaemonicPipe import *
from src.AnnoFit import *

PipelineConfig = json.load(open("config/DaemonicPipeline_config.json", 'rt'))
Logger = DefaultLogger("/dev/null")
