#!/bin/python3

from src.SharedFunctions import *
from src.Initialization import *
from src.DaemonicPipe import *
from src.AnnoFit import *
import glob

files = glob.glob("/_home/_results/The_New_96/MI**/*.final.bam")

PipelineConfig = json.load(open("/dev/datasets/FairWind/.cloud/core/labjournal/tools/Scissors/config/DaemonicPipeline_config.json", 'rt'))
Logger = DefaultLogger("/dev/null")

#lst = ["DCFED13-JULTH13", "DCMIH23-JULTH23", "DCSAN1-QUAR1", "DCVAS3-QUAR3"]

#for item in lst: CoverageStats(f"{item}.FR300", f"/dev/datasets/FairWind/_results/FR300/{item}.FR150.sorted.bam", f"/dev/datasets/FairWind/_results/FR300/{item}.FR150.stats.txt", PipelineConfig["Capture"], PipelineConfig["NotCapture"], PipelineConfig["Reference"], Logger)

for item in files:
	CoverageStats(os.path.basename(item), item, os.path.join(os.path.dirname(item), "new_stats.txt"), "/dev/datasets/FairWind/_db/DinaraPanel_sorted.bed", "/dev/datasets/FairWind/_db/NOTDinaraPanel_sorted.bed", PipelineConfig["Reference"], Logger)
	#ANNOVAR(item, item + ".tsv", PipelineConfig["AnnovarDatabases"], PipelineConfig["AnnovarDBFolder"], PipelineConfig["AnnovarFolder"], PipelineConfig["GenomeAssembly"], Logger, Threads=PipelineConfig["Threads"])
	#AnnoFit(item + ".tsv", item + ".xlsx", PipelineConfig["HGMDPath"], PipelineConfig["AnnovarFolder"], PipelineConfig["AnnoFitConfig"], Logger, PipelineConfig["AnnofitChunkSize"], Threads=PipelineConfig["Threads"])

# gatk FastqToSam -F {R1} -F2 {R2} -O {uBAM} --SAMPLE_NAME S1
# gatk MarkIlluminaAdapters -I {uBAM} --M {MarkAdaptersMetrics} -O {uBAMxt}
# gatk SamToFastq -I {uBAMxt} -F {TrimmedR1} --F2 {TrimmedR2} --CLIPPING_ACTION X --CLIPPING_ATTRIBUTE XT
#
