#!/bin/python3

from src.SharedFunctions import *
from src.Initialization import *
from src.DaemonicPipe import *
from src.AnnoFit import *

PipelineConfig = json.load(open("/dev/datasets/FairWind/.cloud/core/labjournal/tools/Scissors/config/DaemonicPipeline_config.json", 'rt'))
Logger = DefaultLogger("/dev/null")

#lst = ["DCFED13-JULTH13", "DCMIH23-JULTH23", "DCSAN1-QUAR1", "DCVAS3-QUAR3"]

#for item in lst: CoverageStats(f"{item}.FR300", f"/dev/datasets/FairWind/_results/FR300/{item}.FR150.sorted.bam", f"/dev/datasets/FairWind/_results/FR300/{item}.FR150.stats.txt", PipelineConfig["Capture"], PipelineConfig["NotCapture"], PipelineConfig["Reference"], Logger)

ANNOVAR("/dev/datasets/FairWind/_results/JulyThirteen_BGI/20-22_intersect/0000.vcf", "/dev/datasets/FairWind/_results/JulyThirteen_BGI/20-22_intersect/0000.tsv", PipelineConfig["AnnovarDatabases"], PipelineConfig["AnnovarDBFolder"], PipelineConfig["AnnovarFolder"], PipelineConfig["GenomeAssembly"], Logger, Threads=PipelineConfig["Threads"])

AnnoFit("/dev/datasets/FairWind/_results/JulyThirteen_BGI/20-22_intersect/0000.tsv", "/dev/datasets/FairWind/_results/JulyThirteen_BGI/20-22_intersect/0000.xlsx", PipelineConfig["HGMDPath"], PipelineConfig["AnnovarFolder"], PipelineConfig["AnnoFitConfig"], Logger, PipelineConfig["AnnofitChunkSize"], Threads=PipelineConfig["Threads"])

# gatk FastqToSam -F {R1} -F2 {R2} -O {uBAM} --SAMPLE_NAME S1
# gatk MarkIlluminaAdapters -I {uBAM} --M {MarkAdaptersMetrics} -O {uBAMxt}
# gatk SamToFastq -I {uBAMxt} -F {TrimmedR1} --F2 {TrimmedR2} --CLIPPING_ACTION X --CLIPPING_ATTRIBUTE XT
#
